stages:
  generate_data:
    cmd: PYTHONPATH=src ./scripts/generate_data.sh
    outs:
      - data/raw

  validate_data:
    cmd: PYTHONPATH=src ./scripts/validate_data.sh
    deps:
      - data/raw

  prepare_data:
    cmd: PYTHONPATH=src ./scripts/prepare_data.sh
    deps:
      - data/raw
    outs:
      - data/processed/users_clean.csv
      - data/processed/events_clean.csv
      - data/processed/user_daily.csv

  build_features:
    cmd: PYTHONPATH=src ./scripts/build_features.sh
    deps:
      - data/processed/user_daily.csv
    outs:
      - data/features/user_features_daily.csv

  build_labels:
    cmd: PYTHONPATH=src ./scripts/build_labels.sh
    deps:
      - data/processed/user_daily.csv
    outs:
      - data/processed/labels_daily.csv

  build_training_set:
    cmd: PYTHONPATH=src ./scripts/build_training_set.sh
    deps:
      - data/features/user_features_daily.csv
      - data/processed/labels_daily.csv
    outs:
      - data/features/training_dataset.csv

  train_baseline:
    cmd: PYTHONPATH=src ./scripts/train_baseline.sh
    deps:
      - data/features/training_dataset.csv
    outs:
      - artifacts/models
      - artifacts/metrics

  batch_score:
    cmd: PYTHONPATH=src ./scripts/batch_score_latest.sh
    deps:
      - data/features/user_features_daily.csv
      - artifacts/models/production_latest.joblib
    outs:
      - data/predictions
